PROJECT=calculator_3rd_secular_cumulant

MPI_PROJECT=TRUE

DEPENDENCIES=\
toolsIO \
dvector3d \
dvectorNd \
dtensor3x3 \
interaction \
toolsInterpolate \
toolsInterpolate2d \
correlation4points \
feinman2sideddiagram3 \
toolsFFT \
asymptoticLF \
interpolationF2d \
averages_orient \
propagatorM \
numericalSD \
eigen \
constants \
complexv \
calculator_redfield \
constructor-f-exciton \
constructor-f-exciton-gij \
communicator_3rd


include ../make.inc
