PROJECT=calculator_abs_wf

MPI_PROJECT=FALSE

DEPENDENCIES=\
toolsIO \
dvector3d \
dvectorNd \
dtensor3x3 \
interaction \
toolsInterpolate \
toolsInterpolate2d \
toolsFFT \
asymptoticLF \
interpolationF2d \
averages_orient \
numericalSD \
eigen \
constants \
complexv \
calculator_redfield \
constructor-f-exciton \
constructor-f-exciton-gij \
feinman2sideddiagram1 \
communicator_3rd \
calculator_abs_secular_cumulant\
propagatorExciton \
propagatorM \
propagatorMemory\
propagatorExcitonWF\
toolsRandom

include ../make.inc

