PROJECT=propagatorExciton

DEPENDENCIES= dvector3d dvectorNd dtensor3x3 storage complexv constants \
eigen toolsFFT \
communicator_3rd\
numericalSD\
constructor-f-exciton constructor-f-exciton-gij calculator_redfield \
asymptoticLF interpolationF interpolationF2d toolsInterpolate toolsInterpolate2d \
propagatorMemory propagatorM \
toolsIO

include ../make.inc

