PROJECT=calculator_abs_secular_cumulant

DEPENDENCIES=toolsIO \
dvector3d \
dvectorNd \
dtensor3x3 \
interaction \
feinman2sideddiagram1 \
toolsFFT \
asymptoticLF \
averages_orient\
constants \
numericalSD \
calculator_redfield \
complexv \
eigen \
communicator_3rd \
constructor-f-exciton \
constructor-f-exciton-gij \
interpolationF2d \
interpolationF \
toolsInterpolate \
toolsInterpolate2d

include ../make.inc
