PROJECT=calculator-main

BINARY=TRUE

DEPENDENCIES=\
toolsIO \
dtensor3x3 \
dvector3d \
dvectorNd \
toolsInterpolate \
toolsInterpolate2d \
correlation4points \
toolsFFT \
asymptoticLF \
interpolationF2d \
averages_orient \
propagatorM \
constructor-f-exciton \
constructor-f-exciton-gij \
numericalSD \
eigen \
constants \
complexv \
calculator_redfield \
calculator_abs_secular_cumulant \
calculator_abs_wf \
calculator_abs_reduced \
calculator_3rd_secular_cumulant \
calculator_3rd_wf \
calculator_3rd_reduced \
communicator_3rd \
feinman2sideddiagram1 \
feinman2sideddiagram3\
propagatorExciton \
propagatorMemory \
toolsRandom \
interaction 

include ../make.inc
