PROJECT=calculator_redfield

DEPENDENCIES=\
toolsIO \
toolsInterpolate \
toolsFFT \
asymptoticLF \
propagatorM \
numericalSD \
eigen \
constants \
complexv \
communicator_3rd \
dvector3d \
dvectorNd \
dtensor3x3 \
constructor-f-exciton \
constructor-f-exciton-gij \
interpolationF2d \
toolsInterpolate2d 

include ../make.inc
