PROJECT=calculator_abs_reduced

DEPENDENCIES=toolsIO \
dvector3d \
dvectorNd \
dtensor3x3 \
interaction \
toolsFFT \
asymptoticLF \
averages_orient\
constants \
numericalSD \
calculator_redfield \
complexv \
eigen \
communicator_3rd \
constructor-f-exciton \
constructor-f-exciton-gij \
calculator_abs_secular_cumulant \
feinman2sideddiagram1 \
interpolationF2d \
toolsInterpolate2d \
toolsInterpolate \
propagatorExciton \
propagatorMemory \
propagatorM

include ../make.inc
