PROJECT=communicator_3rd

DEPENDENCIES=\
toolsIO \
dtensor3x3 \
dvector3d \
dvectorNd \
toolsInterpolate \
toolsInterpolate2d \
correlation4points \
toolsFFT \
asymptoticLF \
interpolationF2d \
averages_orient \
propagatorM \
constructor-f-exciton \
constructor-f-exciton-gij \
numericalSD \
eigen \
constants \
complexv \
calculator_redfield 

include ../make.inc
