PROJECT=propagatorExcitonWF

DEPENDENCIES= dvector3d dvectorNd dtensor3x3 storage complexv constants \
eigen toolsFFT \
communicator_3rd \
numericalSD\
constructor-f-exciton constructor-f-exciton-gij \
asymptoticLF interpolationF toolsInterpolate interpolationF2d toolsInterpolate2d \
calculator_redfield \
toolsIO toolsRandom

include ../make.inc

