PROJECT=calculator_3rd_reduced

MPI_PROJECT=FALSE

DEPENDENCIES=\
toolsIO \
dvector3d \
dtensor3x3 \
dvectorNd \
interaction \
toolsInterpolate \
toolsInterpolate2d \
correlation4points \
feinman2sideddiagram3 \
toolsFFT \
asymptoticLF \
interpolationF2d \
averages_orient \
numericalSD \
eigen \
constants \
complexv \
calculator_redfield \
constructor-f-exciton \
constructor-f-exciton-gij \
communicator_3rd \
calculator_3rd_secular_cumulant\
propagatorExciton \
propagatorM \
propagatorMemory


include ../make.inc
